### ISSUE TITLE
入站不通

### ISSUE THREAD

**Issue by wy2919** [josexy/cropstun#3]
您好 我能请教您个问题吗？

从服务器发起的连接可以正常经过tun网卡到达HandleTCPConnection函数处理，但是从别的的服务器访问当前服务器的话就会一直阻塞，入站请求的返回应该也会经过tun网卡，但是没有到达HandleTCPConnection函数，您可以指点我一下吗？对于这种外部连接应该如何处理，十分感谢

**Comment by josexy** [comment]
如果设置tun.Options.AutoRoute为true，那么会自动创建路由表和路由规则（通过 ip route show table all 和 ip rule list查看）。
比如：
```shell
❯ ip rule list
0:	from all lookup local
10086:	from all to 198.18.0.0/16 lookup 4000
10087:	from all lookup 4000
10088:	not from all dport 53 lookup main suppress_prefixlength 0
10088:	from all iif utun5 goto 10096
10089:	not from all iif lo lookup 4000
10089:	from 0.0.0.0 iif lo lookup 4000
10089:	from 198.18.0.0/16 iif lo lookup 4000
10096:	from all lookup 10
32766:	from all lookup main
32767:	from all lookup default
```
一般来说tun主要用于本地client模式，如果想要外部经过tun虚拟网卡，可以试试下面的方法
```shell
# 删除10087的路由规则 from all lookup 4000
sudo ip rule del preference 10087
# 并转发enp0s5数据包到tun设备
sudo iptables -t nat -A PREROUTING -i enp0s5 -j DNAT --to-destination 198.18.0.2
```
上面的命令参数可能需要自行修改下。

**Comment by wy2919** [comment]
> 如果设置tun.Options.AutoRoute为true，那么会自动创建路由表和路由规则（通过ip route show table all和ip规则列表查看）。 比如：
> 
> ```shell
> ❯ ip rule list
> 0:	from all lookup local
> 10086:	from all to 198.18.0.0/16 lookup 4000
> 10087:	from all lookup 4000
> 10088:	not from all dport 53 lookup main suppress_prefixlength 0
> 10088:	from all iif utun5 goto 10096
> 10089:	not from all iif lo lookup 4000
> 10089:	from 0.0.0.0 iif lo lookup 4000
> 10089:	from 198.18.0.0/16 iif lo lookup 4000
> 10096:	from all lookup 10
> 32766:	from all lookup main
> 32767:	from all lookup default
> ```
> 
> tun主要用于本地客户端模式，如果想要外部经过tun虚拟中断，可以大致尝试下面的方法
> 
> ```shell
> # 删除10087的路由规则 from all lookup 4000
> sudo ip rule del preference 10087
> # 并转发enp0s5数据包到tun设备
> sudo iptables -t nat -A PREROUTING -i enp0s5 -j DNAT --to-destination 198.18.0.2
> ```
> 
> 修改上面的命令参数可能需要自行下。

感谢您的回复！

我删除了 10087 后确实外部服务器可以正常返回了，我想了想应该是from all lookup 4000不仅仅会拦截从服务器发出的请求，还会拦截服务器响应的请求

我是想编写一个流量管控程序，主要是针对上行流量，当服务器流量消耗到一定值后程序进行介入，通过tun网卡拦截所有出站请求并对部分白名单进行放行，从服务器主动发出的请求是可以通过tun网卡正常拦截的，但是这种服务器被动响应的是可以进入tun，但是不知如何处理这种响应数据包，响应应该是在成功建立TCP连接之后才能响应，不知道用gvisor该如何处理，可能这种需求通过iptables更好实现，但是我还是想了解tun网卡是否有能力实现这种功能

我观察了您程序创建的路由规则，在删除了from all lookup 4000后服务器本机发出的请求可以正常通过tun走到go中，服务器响应的请求不会走到tun中，我测试后发现对于服务器本机发出的请求拦截主要是from 0.0.0.0 iif lo lookup 4000 和 from 192.168.0.0/16 iif lo lookup 4000这2条规则的作用，删除其中一个后都会导致tun拦截失效，我不太明白为什么和lo接口有关系，难道是本机发出的请求都是通过lo发出的吗？

再次感谢占用了您的时间给予我回复

**Comment by josexy** [comment]
不知道你说的是不是这种情况：当请求进入tun后，处理这个请求并返回响应数据包给对端，如何处理可以参考 mini-ss(https://github.com/josexy/mini-ss/blob/13a8f29bd6d1a26e07fd9dc87698517bfe247fee/enhancer/handler.go#L43) 或者 clash meta(https://github.com/MetaCubeX/mihomo/blob/a034421a58674dd80399702de657250910bfeac3/listener/sing_tun/dns.go#L45) 。简单来说就是在HandleTCPConnection里面建立双向TCP隧道，转发src和dst之间的数据（为了避免路由循环，需要连接dst之前bind出站网卡）

拦截本机请求主要靠 `from all to 192.168.0.0/16 lookup 4000` 和 `from all lookup 4000` 这两条规则，而 `from 0.0.0.0 iif lo lookup 4000` 和 `from 192.168.0.0/16 iif lo lookup` 应该是在前面的规则被删除后兜底用的（优先级一样），有无 iif lo 应该没太大关系。所以如果这个也删除了，那么会匹配失败而不经过tun网卡

**Comment by wy2919** [comment]
> 不知道你说的是不是这种情况：当请求进入tun后，处理这个请求并返回响应数据包给对端，如何处理可以参考mini-ss( [https://github.com/josexy/mini-ss /blob/13a8f29bd6d1a26e07fd9dc87698517bfe247fee/enhancer/handler.go#L43](https://github.com/josexy/mini-ss/blob/13a8f29bd6d1a26e07fd9dc87698517bfe247fee/enhancer/handler.go#L43) ) 或者冲突元( [https://github.com/MetaCubeX/mihomo/blob/a034421a58674dd80399702de657250910bfeac3/listener/sing_tun/dn](https://github.com/MetaCubeX/mihomo/blob/a034421a58674dd80399702de657250910bfeac3/listener/sing_tun/dns.go#L45) s.go#L45 ) 。简单来说就是在HandleTCPConnection里面建立每个TCP隧道，转发src和dst之间的数据（为了避免路由循环，需要连接dst之前bind出站阻塞）
> 
> 拦截本机请求主要靠`from all to 192.168.0.0/16 lookup 4000`和`from all lookup 4000`这前置规则，而`from 0.0.0.0 iif lo lookup 4000`应该`from 192.168.0.0/16 iif lo lookup`是在前面的规则被删除后兜底用的（优先级一样），有无 iif lo 应该没什么专业关系。所以如果这个也删除了，那么会匹配失败而不经过退款

感谢回复 我去研究下
